server:
  port: ${PORT:8080}
  hostname: localhost
spring:
  application:
    name: rightstep
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    h2:
      console:
        enabled: true
        path: /h2
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_PATH:postgresql://localhost:5432/db_rs?dialect=PostgreSQL10Dialect}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:123456}
  flyway:
    baseline-on-migrate: true
    clean: true
    encoding: UTF-8
    enabled: true
    user: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:123456}
    url: jdbc:${DATABASE_PATH:postgresql://localhost:5432/db_rs?dialect=PostgreSQL10Dialect}
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
logging:
  level:
    org.springframework.web: ERROR
    ru.kuznetsovka.rigthStepTest: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /log/app.log









