CREATE TABLE  tbl_circles (
  id int8 generated by default as identity,
  color varchar(255),
  radius float8 not null,
primary key (id));
CREATE TABLE tbl_rectangles (
  id int8 generated by default as identity,
  color varchar(255),
  length float8 not null,
  width float8 not null,
primary key (id));
